### ISSUE TITLE
axis labels rotated 90 degrees?

### ISSUE THREAD

**Issue by aaelony** [yieldbot/vizard#1]
Very nice tool.  Is it possible to allow for x-axis labels to be rotated 90 degrees?  
The setting in vega might be `axes -> labels -> "angle": {"value": 90}`.

cheers,
A

**Comment by sorenmacbeth** [comment]
Hello, the spec generated by the `vizard` function in just a clojure map representation of a json vega spec, so you can just `update-in` in the appropriate place and then pass the new map into the `plot!` function.

There is an example of doing this in the blog post here: https://www.yieldbot.com/blog/yieldbot-launches-vizard-for-data-visualization/

**Comment by aaelony** [comment]
Hi, thanks that's perfect!  

works nicely with a variant of the following

```
(-> (plot/vizard { default-spec } )
         (update-in [:axes] merge { some-new-spec } ))
```

Thanks,
A
