### ISSUE TITLE
Common/Top Level properties removed???

### ISSUE THREAD

**Issue by jsa-aerial** [yieldbot/vizard#11]
I cannot seem to get some of the simplest common and top level properties to make into plots. Here is a really simple example from Vega-Lite documentation:

(->
   {:title "A Simple Bar Chart"
    :data {:values
           [{:a "A", :b 28}, {:a "B",:b 55}, {:a "C",:b 43},
            {:a "D", :b 91}, {:a "E",:b 81}, {:a "F",:b 53},
            {:a "G", :b 19}, {:a "H",:b 87}, {:a "I",:b 52}]
           },
    :mark "bar",
    :encoding {:x {:field "a", :type "ordinal"},
               :y {:field "b", :type "quantitative"}}}
   p!)

This will plot the bar chart, but without the title. Same with background color - no effect. OTOH, other simple cases like :width and :height do work.

I'm thinking something is messed up on the client side, as the return data from p! has the map with these properties in it. last-vl-spec also returns the map with all elements correctly contained.

**Comment by sorenmacbeth** [comment]
what do you mean `without the title`? :title is just notation and doesn't get actually drawn into the plot. also if you could attach a png or svg of the output for each spec, along with the output of `p!` for each one you are trying to render that would be great.

**Comment by jsa-aerial** [comment]
Just that - no title. :title is a legal vl property for view specs - it should get turned into a legal vega mark for the chart title. Have a look at this https://vega.github.io/vega-lite/docs/title.html, where you can jump to see a live version working just fine in a vega editor.

Same issue with other common/top-level properties (background, ...) 
https://vega.github.io/vega-lite/docs/spec.html#common
but not all - width and height do work

OK, line 58 in vizzard.cljs: (.-spec (js/vl.compile (clj->js vl-spec)))
is where it goes wrong. This appears to actually be from vega-lite itself. Maybe this is a version issue?

You can _very_ easily see this issue by taking the original simple example I gave above and then either look at the network frames in chrome inspect (or equiv) and/or check vizard.server/last-spec after render.

network frames show these two telling bits:
[["~:vizard/vl-spec", ["^ ", "title", "A Simple Bar Chart", "height", 500, "width", 550, "data",…]]]
[["~:vizard/to-vega", ["^ ", "~:width", 1, "~:height", 1, "~:padding", "auto", "~:data",…]]]
(I have no idea why this editor is putting 'cross out' lines over these...)

The first is how the spec came over to :chsk/recv :vizard/vl-spec
The second shows what is sent back as the (compile-vl-spec msg) result.

and for this exact exchange, here is last-spec (no title mark...):

panclus.core> @vizard.server/last-spec
{:width 1, :height 1, :padding "auto", :data [{:name "source", :values [{:a "A", :b 28} {:a "B", :b 55} {:a "C", :b 43} {:a "D", :b 91} {:a "E", :b 81} {:a "F", :b 53} {:a "G", :b 19} {:a "H", :b 87} {:a "I", :b 52}], :format {:type "json", :parse {:b "number"}}, :transform [{:type "filter", :test "datum[\"b\"] !== null && !isNaN(datum[\"b\"])"}]} {:name "layout", :source "source", :transform [{:type "aggregate", :summarize [{:field "a", :ops ["distinct"]}]} {:type "formula", :field "width", :expr "550"} {:type "formula", :field "height", :expr "500"}]}], :marks [{:name "root", :type "group", :from {:data "layout"}, :properties {:update {:width {:field "width"}, :height {:field "height"}}}, :marks [{:name "marks", :type "rect", :from {:data "source"}, :properties {:update {:x {:scale "x", :field "a", :offset 0.5}, :width {:scale "x", :band true, :offset -0.5}, :y {:scale "y", :field "b"}, :y2 {:scale "y", :value 0}, :fill {:value "#4682b4"}}}}], :scales [{:name "x", :type "ordinal", :domain {:data "source", :field "a", :sort true}, :rangeMin 0, :rangeMax 550, :round true, :padding 0.1} {:name "y", :type "linear", :domain {:data "source", :field "b"}, :rangeMin 500, :rangeMax 0, :round true, :nice true, :zero true}], :axes [{:type "x", :scale "x", :grid false, :ticks 5, :title "a", :properties {:labels {:text {:template "{{ datum[\"data\"] | truncate:25 }}"}, :angle {:value 270}, :align {:value "right"}, :baseline {:value "middle"}}}} {:type "y", :scale "y", :format "s", :grid true, :layer "back", :title "b"}]}]}

**Comment by sorenmacbeth** [comment]
you are looking at the vega-lite docs for the rc of vega-lite 2. The release version of vizard is on vega 2 and vega-lite 1.2.

Once vega-lite 2.0 is released, I will release a new version of vizard targeting vega 3/vega-lite 2.0

**Comment by jsa-aerial** [comment]
I noticed vega-lite 2 and vega 3 in the project.clj and but not the 0.3.0-SNAPSHOT and just used the the 'official' 0.2.1 in clojars. AFAICT, according to the vega-lite site, V2 is released. I think I need to just fix this...

**Comment by sorenmacbeth** [comment]
![image](https://user-images.githubusercontent.com/130043/30405353-249a16fe-98a0-11e7-911b-0e98dc3b76ba.png)

As I said, it's in release candidate stage now. It will be released soon. At that time I release a new version of vizard.
