### ISSUE TITLE
Support vega (sans -lite) plots

### ISSUE THREAD

**Issue by metasoarous** [yieldbot/vizard#12]
Seems like it would be pretty easy to add a reagent component - say, `vega` - akin to the `vega-lite` component which would render vega instead of vega-lite. The `p!` function then could either have an option for `vega` vs `vega-lite` (possibly taken from the vega map itself), or you could just have a separate function for lite vs non-lite. Either way, you'd then just make sure to update whatever component is getting rendered in the `application`. Does this sound reasonable?

**Comment by metasoarous** [comment]
I realize this is potentially a little more complicated as whatever translation functions exist may only be implemented in JS, and thus a bit of a pain to access through the JVM, where its most useful. I suppose Nashorn could be used for this, but I haven't ever tried to do such a wrapping, and don't know how difficult it would be.

Short of that, reimplementing the translation would probably be more trouble than its worth.

**Comment by sorenmacbeth** [comment]
Thanks for filing an issue. As of the 1.0.x release, a decision was made to only support vega-lite 2.0 specs. This was for purposes of simplification and the expanded capabilities of vega-lite 2.

You can always use the vega online editor to compile your vega-lite spec to vega and manipulate it that way, but vizard won't support doing that directly.
