### ISSUE TITLE
The documentation doesn't result in a working system

### ISSUE THREAD

**Issue by whodevil** [yieldbot/vizard#2]
Hello,

I'm really excited about this project, I saw @sorenmacbeth give a talk at clojure west last year about something along these lines. 

I ran through the steps on your blog post about vizard and the instructions in the README.md. `(start-plot-server!)` does seem to start a server. However, running the plot command dumps edn out. I'm not sure how to interact with the edn or how to render it in the browser. I'd be happy to help with documentation if you could help me over the hump.

Thanks!

**Comment by whodevil** [comment]
So I cloned the vizard project and ran the commands from there and they appear to work as advertised. Sweet! There must be something going on with the way it is packaged as a library.

**Comment by sorenmacbeth** [comment]
hello,
could you share the project.clj to the project where you tried to use it as a library as well as the commands you ran in the repl?

**Comment by whodevil** [comment]
Ok, well I'm smoking crack I guess because I walked through the steps again this morning and it now appears to work. 

Nothing to see here, move along. 

Sorry for bothering you with my non issue.
