### ISSUE TITLE
Set the x-axis range

### ISSUE THREAD

**Issue by Eleonore9** [yieldbot/vizard#3]
I tried a line and a scatter plot. My values on the x-axis are years (so > 1900). 
How do I make it so that the x-axis doesn't start from 0? Is there an option for that in "encoding"?

**Comment by sorenmacbeth** [comment]
Unfortunately not at the moment. You'd need to capture the generate spec returned from `plot!` and then `update-in` on your x-axis to add `:zero false`.

**Comment by Eleonore9** [comment]
Thanks @sorenmacbeth !

**Comment by Eleonore9** [comment]
@sorenmacbeth is it an `update-in` or `assoc-in`?
And where should `:zero false` go in the generated spec? I tried to add it to the first map inside `:axes` vector or inside `:scales` vector but I don't see any change on the plot.

```
{:height 500,
 :width 960,
 :axes
 [{:scale "x", :type :x, :title nil}
  {:scale "y", :type :y, :title nil}],
 :scales
 [{:name :x,
   :type :linear,
   :domain {:data :line, :field :x},
   :range :width}
  {:name :y,
   :type :linear,
   :nice true,
   :domain {:data :line, :field :y},
   :range :height}
  {:name :color,
   :type "ordinal",
   :domain {:data :line, :field :col},
   :range "category20b"}],
 :marks
 [{:type :group,
   :from {:data :line, :transform [{:type :facet, :groupby [:col]}]},
   :marks
   [{:properties
     {:enter
      {:x {:scale "x", :field :x},
       :y {:scale "y", :field :y},
       :stroke {:scale "color", :field :col},
       :strokeWidth {:value 2}}},
     :type :line}]}],
 :data
 [{:name :line,
   :values
   ({:y 2, :col "foo", :x 2000}
    {:y 3, :col "foo", :x 2001}
    {:y 4, :col "foo", :x 2002})}],
 :legends [{:fill "color"}]}
```

**Comment by sorenmacbeth** [comment]
can you paste the inputs to your `plot!` function please?
