### ISSUE TITLE
Breakage with specter 0.12.0

### ISSUE THREAD

**Issue by luxbock** [yieldbot/vizard#4]
Since `specter` introduced a breaking change in 0.12.0 where `select` and `setval` have been moved to the `com.rpl.specter.macros` namespace, `vizard` can no longer be used together with a project that uses the most recent version of `specter`.

**Comment by sorenmacbeth** [comment]
Thanks for the issue. I'm not sure how I want to solve this yet though. I may completely remove the dependency on specter rather than bumping the version of the dependency.
