### ISSUE TITLE
Uncaught Error: Unrecognized scale range value: "category20b" 

### ISSUE THREAD

**Issue by vspinu** [yieldbot/vizard#8]
I am trying the readme examples from the default lein project and I see `ncaught ReferenceError: goog is not defined` in the browser's console. 

Do I need some special js/clojurescript trickery to make it work?

**Comment by vspinu** [comment]
Ok. Run `lein install` on the snapshot and server seem to start fine. But now I get `vizard.js:13 Uncaught Error: Unrecognized scale range value: "category20b"`. 

Same error when I run nREPL directly from vizard project and run examples from within `vizard/core.clj`.

**Comment by sorenmacbeth** [comment]
The snapshot is a development version targeting the beta version of vega 3 and vega-lite 2. Use the latest release version 0.1.9.

**Comment by vspinu** [comment]
Thanks for pointing in right direction. `0.1.9` works as advertised. `0.2.1` is broken. 

Do you have an example that would work for the snapshot? I would like to hack a bit on this project and try to stick to vega 3 as official docs are for that version.

**Comment by vspinu** [comment]
Ok, I figured that out. It's as easy as 

```clj
(p! (json/parse-stream json-spec keyword))
```
where `json-spec` is veca-lite json spec.

**Comment by sorenmacbeth** [comment]
fwiw, I tested version `0.2.1` with the example in the README and they all worked fine.
